name: Validate boilerplate code
description: Validates that my Node projects still use up-to-date boilerplate code.
author: Jaid
inputs:
  token:
    description: Repository token for allowing the action to make commits.
    required: true
runs:
  using: node12
  main: build/index.js
branding:
  icon: package
  color: yellow
